### ISSUE TITLE
Add helpers for calling pageLoaded event on the client

### ISSUE THREAD

**Issue by oas89** [effector/razzle-template#6]
Update lib/effector.ts with helpers from [accesso](https://github.com/accesso-app/frontend/blob/master/src/lib/page-routing.ts):

- typings for start event
- hook useStart for emitting start event on the client
- createStart factory for creating start event

**Comment by OlegBrony** [comment]
I thins it's already done by [this](https://github.com/effector/razzle-template/pull/8) merge request. can you check it?

**Comment by sergeysova** [comment]
I closing this issue because #8 implemented it
